name: testing
on:
  pull_request:
  merge_group:
  schedule:
    - cron: '55 2 * * *'  # 2:55am-ish UTC everyday (approx 50 minutes after akmods images run)
  workflow_dispatch:

jobs:
  build-testing:
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    with:
      coreos_version: testing
